title: ClinTrialConnect
author:
  name: 'ClinTrialApp, LLC'
  email: sales@clintrialapp.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Clinical trials can be complex. ClinTrialConnect helps educate patients about clinical trials and their disease. In addition, it provides background information about the pharmaceutical or medical device company, and detailed information about what to expect from a specific clinical trial.'
  keywords: 'clinical, trials, education, connection, connect, help, pharma, doctors, physicians, help, language, patients'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
